### ISSUE TITLE
On mobile, put filters in flyout/overlay

### ISSUE THREAD

**Issue by jlow81** [GSA/code-gov-front-end#103]
## Expected Behavior

On mobile, instead of having all the filters displayed by default there should be a filter button that reveals all filters with a flyout out or overlay menu. Right now the filters take up too much real estate and push the main content too far down so the user has to scroll too much.

## Current Behavior

All filters are displayed on mobile pushing the main content of the page way down

## Possible Solution

Create a Filter button, and when clicked the filters will fly in and fill the screen.

See: https://a4alzb.axshare.com/filters.html

## Additional Context
Previous work was done on the Angular version of the site and some of it can probably be copied over: https://github.com/GSA/code-gov-web/pull/702/files

**Comment by DanielJDufour** [comment]
Hi, @mriqooo .  Would you like to still work on this?  As you may have noticed we changed our code base over to React recently.  Thanks again for your interest! :-)

**Comment by mriqooo** [comment]
No i don't work on this. I onyl waiting for merge approve. Sorry but i
don't have any experience with react

**Comment by DanielJDufour** [comment]
No worries.  Thank you for your pull request.  I'll make sure whoever works on this next sees it and will take some of the good .scss work that you did! :-)

For others, the pull request can be found here: https://github.com/GSA/code-gov-web/pull/702/files

**Comment by jcastle** [comment]
USWDS should help with this.
