### ISSUE TITLE
multilingual support?

### ISSUE THREAD

**Issue by viymak** [GSA/code-gov-front-end#105]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Expected Behavior

I think it would be beneficial if code.gov could be viewed in other languages such as Spanish.
## Current Behavior

there is no way to change the language
## Possible Solution

not sure

## Steps to Reproduce (for bugs)

1.go to code.gov

## Context

This hasn't affected me personally, but may be useful to those who are more comfortable in another language.

**Comment by ftonato** [comment]
Hello everyone

I really want to express my points about it:

- I think we should just translate the core (titles, descriptions, and links ~nav items label~), ignoring everything related to the projects (titles and descriptions);
- The most controversial point is, who will maintainer this multilingual updated?
  - This can be an unnecessary effort if we do not have someone to maintain each lang...

----
I want to help to work on this issue, but we should think about the problem that we may be creating.

/cc @DanielJDufour

**Comment by jcastle** [comment]
Closing. This is not a high priority for us. Great suggestion.
