### ISSUE TITLE
Center search results header on Open Tasks

### ISSUE THREAD

**Issue by saracope** [GSA/code-gov-front-end#110]
**Describe the bug**

The search results header is too far left. 

<img width="473" alt="screen shot 2018-12-06 at 12 08 54 pm" src="https://user-images.githubusercontent.com/2197515/49599952-25b32f00-f950-11e8-9d53-b88062e12dd2.png">

**Fix**
Center the header.
Adding` text-align: center` to `.search-results-header` should fix it.

<img width="1334" alt="screen shot 2018-12-06 at 12 10 37 pm" src="https://user-images.githubusercontent.com/2197515/49600025-4ed3bf80-f950-11e8-8594-210bdc284774.png">

**Comment by ScottSauceda** [comment]
I want to work on this.
