### ISSUE TITLE
Fix mobile menu for FSCP

### ISSUE THREAD

**Issue by saracope** [GSA/code-gov-front-end#111]
**Describe the bug**

The mobile menu for the subnav on the Federal Source Code Policy page should be updated to increase the tap target.

![img_e5471b2f1508-1](https://user-images.githubusercontent.com/2197515/49602146-b9d3c500-f955-11e8-9262-16c0ad581a07.jpeg)

**Fix**
Edit this menu so that it is more easily tapped by the user. Similar to the Browse Project nav on the home page.
![img_4567](https://user-images.githubusercontent.com/2197515/49602094-9c066000-f955-11e8-8b8f-ef7b270a5ab4.PNG)

It should also be updated to use a [`nav` html tag](https://html.spec.whatwg.org/multipage/sections.html#the-nav-element).

**Comment by DanielJDufour** [comment]
@saracope , what device is this on?  It's appearing as a select dropdown on my Samsung S5

**Comment by saracope** [comment]
Oh, I see, it's just not rendering right in chrome. I'll update this.
