### ISSUE TITLE
Replace Custom Syncers with Reselect

### ISSUE THREAD

**Issue by DanielJDufour** [GSA/code-gov-front-end#114]
**Is your feature request related to a problem? Please describe.**

We're currently using an anti-pattern of listening to the store and updating search results whenever the params change.

**Describe the solution you'd like**

We should be using the popular [reselect](https://github.com/reduxjs/reselect) rather than custom code.

**Describe alternatives you've considered**

Keep things the way they are, but negative to this is that it is harder for new contributors to figure out what is going on, it's increasing the amount of code that needs to be maintained and there's no guarantee redux won't change and break this weird current syncing solution.

**Additional context**

Custom atypical Sync Function: https://github.com/GSA/code-gov-front-end/blob/master/src/sync-store.js
Custom Store Triggers: https://github.com/GSA/code-gov-front-end/blob/master/src/syncers.js
Reselect Library: https://github.com/reduxjs/reselect

**Comment by DanielJDufour** [comment]
I'll do this.

**Comment by DanielJDufour** [comment]
Darn.  Upon further investigation it appears that reselect is not our answer for syncing browse and search results with the user filter and page selections.  From https://github.com/reduxjs/reselect/issues/142: 
```
Reselect is not intended for this use case, it is for computed derived data from data that is already in the store. Try looking at Redux Thunk or, if more complicated orchestration is required, Redux Saga or Redux Loop.
```

Perhaps, redux-saga is the answer? https://github.com/redux-saga/redux-saga  I'll investigate although it appears that it does not support memoization out of the box.

**Comment by jcastle** [comment]
Going to close for now since this is stale and not on the short-term radar.
