### ISSUE TITLE
Define site.json schema using JSON Schema

### ISSUE THREAD

**Issue by DanielJDufour** [GSA/code-gov-front-end#121]
**Is your feature request related to a problem? Please describe.**

Reusers can't tell if they've properly filled out the site.json without tedious manual inspection

**Describe the solution you'd like**

Make schema specification for site.json using JSON Schema just like code.json and use validator just like code.json

**Describe alternatives you've considered**

Leave as is

**Additional context**

**Comment by jcastle** [comment]
Reworking schema and schema validator. Currently removed from front-end.
