### ISSUE TITLE
[Suggestion] Add ESLint for code quality

### ISSUE THREAD

**Issue by ftonato** [GSA/code-gov-front-end#135]
Hello, this can catch fire 🔥 👩‍🚒 👨‍🚒 🚒

> First, it's important to remind you that I'm not part of the @team (yet haha) that keeps this project, I'm just trying to help 😇

----
Every medium/large project could be chaos, for this reason, it's important to ensure a minimum organization.

My current suggestion is to add a `{ codeQuality }` process, for now, I'm thinking about ESLint...

**Is your feature request related to a problem? Please describe.**
Each developer does the code of your way, so would be interesting to keep the base organized regardless of the personal preference of each one...

**Describe the solution you'd like**

My solution is add ESLint, 
1. Add _ESLint_;
2. Fix some problems*
2.1. Add warnings to unresolved issues
3. Avoid new commits/pull-requests with errors
4. When time is up, remove all rules that show warnings and fix them.

**Additional context**
If you don't think my solution would be cool, please, consider reading it:
- [Why (and how) to use eslint in your project](https://medium.com/the-node-js-collection/why-and-how-to-use-eslint-in-your-project-742d0bc61ed7)
- [Why you should always use a Linter](https://medium.com/dailyjs/why-you-should-always-use-a-linter-and-or-pretty-formatter-bb5471115a76)
- [Understanding the Real Advantages of Using ESLint](https://blog.rangle.io/understanding-the-real-advantages-of-using-eslint/)

**Comment by saracope** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement tests on front-end](https://trello.com/c/Oq8Qqv5A/1196-implement-tests-on-front-end)
