### ISSUE TITLE
Link to Code.gov procurement page, not Code.gov home 

### ISSUE THREAD

**Issue by Karentrebon** [GSA/code-gov-front-end#145]
Code.gov link here
https://code.gov/about/open-source/licensing 
Should probably go to procurement page, not Code.gov home 
https://code.gov/about/compliance/procurement

**Comment by DanielJDufour** [comment]
I fixed this with https://github.com/GSA/code-gov-about-page/pull/4.  Here's the steps to update:
1) Merge PR
2) Update version in https://github.com/GSA/code-gov-about-page/blob/master/package.json
3) Republish @code.gov/about-page
4) Updated dependency version in https://github.com/GSA/code-gov-front-end/blob/master/package.json

Let me know if you have any Qs :-)

**Comment by saracope** [comment]
Merged @DanielJDufour's update into master, thanks!
