### ISSUE TITLE
Footnote color not consistent

### ISSUE THREAD

**Issue by Karentrebon** [GSA/code-gov-front-end#146]
#2 footnote doesn’t show in blue like other numbers  
https://code.gov/policy-guide/introduction

**Comment by DanielJDufour** [comment]
Issue is with Federal Source Code Policy Plugin.  I created an issue there: https://github.com/GSA/code-gov-front-end/issues/146

**Comment by saracope** [comment]
Closing this out since @DanielJDufour created a new issue for it in the component repo.
