### ISSUE TITLE
Sort repositories by Last Update does not work in browse-projects

### ISSUE THREAD

**Issue by christopher-eddy-state-ca-gov** [GSA/code-gov-front-end#147]
**Describe the bug**
On the browse-projects screen, select Sort By Last Update.  Bug is that the sort does not take place.

**To Reproduce**

The order should have been by last update date.

 - OS:  windows
 - Browser Chrome
 - Version 72.0.3626.109 (

**Comment by wodaen** [comment]
Please close the main issue. This bug seems to have been fixed.
