### ISSUE TITLE
Pagination controls are not working in recent versions of Firefox on Windows

### ISSUE THREAD

**Issue by binlabs** [GSA/code-gov-front-end#149]
**Describe the bug**

None of the controls for pagination at the bottom of the Browse Projects page are working in Firefox.

**To Reproduce**
1. Go to https://code.gov/browse-projects?page=1&size=10&sort=data_quality
2. Scroll to the bottom of the initial 10 results
3. Click on any of the pagination controls (e.g. a page number, or the "Next" button)
4. See the error `TypeError: document.querySelector(...) is null` in the console

**Expected behavior**

Clicking on the pagination controls should result in a changing of the projects listed.

**Desktop (please complete the following information):**
 - Windows 10
 - Firefox
 - 60.5.1esr (64-bit)

**Additional context**

This bug may exist in other browsers, but so far I've only tested it in the Windows version of Firefox 60.5.1esr (64-bit).

**Comment by DanielJDufour** [comment]
Great catch! This is definitely some quirky behavior.  I just downloaded Firefox 65.0.1 on my Mac and it worked.  Could it be that there's a difference between Firefox on Windows versus MacOS?

Some additional questions come to mind:
@binlabs , does this link work for you? https://code.gov/browse-projects?&page=2&size=10&sort=data_quality

Could you take a screenshot of your browser after you click next?  Do you know if the url updates and no new content is shown? Or is the URL never updated?

Thank you for finding this tricky bug!

**Comment by binlabs** [comment]
@DanielJDufour First, to answer your questions:

1. The link you provided DOES work in Windows Firefox. Changing the page number in the URL and manually navigating there will display the correct set of projects (In this case, the projects that are currently on page 2)
2. The URL parameters DO NOT change after clicking the Next button or an individual page. The screenshot below was taken immediately after clicking the Next button.

<img width="877" alt="windows-firefox-after-clicking-next-button" src="https://user-images.githubusercontent.com/1139848/53283943-dab8e480-3712-11e9-88a4-10e8ddee6d8d.png">

#### Notes
1. Like you, I can confirm the pagination controls work just fine on MacOS Firefox
2. I've verified this issue with Windows Firefox by using a second machine (which is where the screenshots are from), and Firefox on this machine does not have any addons or extensions, so we can eliminate the possibility of Firefox extensions causing the issue. There must actually be some difference between the MacOS and Windows Firefox versions, perhaps in the Javascript engine.

### Additional Finding
I have stumbled upon another issue in Windows Firefox on the Browse Projects page that is incredibly obvious, but I somehow missed it until now: I have a feeling this is related to the issue we are discussing, but if you think I should open a new Issue, please let me know.

The Filter boxes in the left column are missing entirely. On page load this Javascript error is being output:

`ReferenceError: customElements is not defined
code-gov-web-components.js:74:3`

There are also two custom errors being output with `console.error()` to show the objects for `client.tasks` and `client.repos`, but the objects they are outputting actually look fine to someone unfamiliar with the codebase, but maybe they will give you more insight. You can see all 3 errors in the console in the screenshot below.

<img width="947" alt="windows-firefox-browse-projects-filters-missing" src="https://user-images.githubusercontent.com/1139848/53284164-e063f980-3715-11e9-9614-7aac4859bcd1.png">

Annotation in red is mine, of course.

**Comment by jcastle** [comment]
Looks like they work now. Maybe a more recent update to Firefox that supports the controls is in place. Closing because I can't replicate the issue.
