### ISSUE TITLE
Filtering Projects by Programming Language Bug

### ISSUE THREAD

**Issue by AminPIC** [GSA/code-gov-front-end#151]
**Describe the bug**
When using the Filters in the Browse Projects section of Code.gov and selecting Filter by Language (and selecting C++), no C++ projects populate in the results section.

**To Reproduce**
1. Go to 'code.gov'
2. Click on 'Browse Projects'
3. Under Filters Select Language Filter and Click on C++
4. See error that no projects come up

**Expected behavior**
The expected behavior is that if no such projects for a particular filter (in this case C++ language) exist, then the ability to filter by that selection should not exist. In other words, C++ should not be an option here since there are no projects that use that language.

**Screenshots**
![screen shot 2019-02-27 at 1 47 06 pm](https://user-images.githubusercontent.com/24941490/53515068-22cf6280-3a97-11e9-8231-bdabeb541260.png)

**Desktop (please complete the following information):**
 - OS: High Sierra
 - Browser: Chrome
 - Version 69.0.3497.100 (Official Build) (64-bit)

**Additional context**
I'm assuming this is a front-end matter and that there are in fact no C++ projects

**Comment by goigle** [comment]
The issue happens with C# too

**Comment by ftonato** [comment]
Hi @saracope,

I investigated this problem and the conclusion is, follow the data flow:

1. Go to { Browser Projects } page
1.1 [GET] to { assets/data/filters/repos.json }
1.2 [Response] _JSON_ with a prop named: `languages` with many values *(e.g.: `assembly`, `C`, `C#`, `C++`, ...)*
2. We create our sidebar based on the `values` of the prop `languages`.
3. When we do a filter based on one specific language that doesn't have data, we receive this response: `{ "total": 0, "repos": [] }`.

I think the approach requested by @AminPIC is a best idea:
> In other words, C++ should not be an option here since there are no projects that use that language.

**BUT**, currently our strategy is based on not add "unnecessary logic" to backend, with this mindset we created our static JSON with many possibilities of languages, so in my opinion:

> **If the API doesn't have data to show, would be interesting show a message to our users.**
> by @ftonato 

![Screenshot at 2019-03-22 22-01-58](https://user-images.githubusercontent.com/5417662/54855432-31074c00-4cee-11e9-905f-98fa43014b3a.png)
This empty space is not friendly, our users have a bad experience (this issue, reported by two people, thanks for it [@AminPIC, @goigle], can prove my points).

---

The message should be thought/created by our UX/Designers, but we can suggest something, I suggest this one:

Unfortunately we still don't have any projects with this filters, but you can suggest projects that you find interesting with this specifications:

- Selected filter item [1]
- Selected filter item [2]
- Selected filter item [3]

> Click here to add a request for this
> Thank you for your contribution!

**Comment by hendersonanalytics** [comment]
@saracope @AminPIC There are actually repos that use C++:
https://github.com/GSA/code-gov-front-end/issues/161#issuecomment-491959496

You're not seeing any results for C++ because the language query string isn't being properly encoded by the api client: https://github.com/GSA/code-gov-api-client/issues/16

When that api client issue is resolved this no results issue will no longer exist.

**Comment by hendersonanalytics** [comment]
The C++ issue was addressed in a [recent PR](https://github.com/GSA/code-gov-api-client/pull/18) and should now be visible.  There is still at least one language filter (SAS) that doesn’t return any repos.  That issue is still under investigation.
