### ISSUE TITLE
Compliance Dashboard List Missing NSF 

### ISSUE THREAD

**Issue by RicardoAReyes** [GSA/code-gov-front-end#152]
The Code.gov Compliance Dashboard list does not show the National Science Foundation agency. The agency_metadata.json file does have NSF on the JSFON file. Record #19 with id=20 and complianceDashboard = true. 

** To Reproduce **
1. Go to https://code.gov/about/compliance/dashboard
2. The list shows 23 of 24 CFO Act Agencies.
3. National Science Foundation is missing

**Comment by DanielJDufour** [comment]
If you haven't found it yet, you'll want to add NSF to the onDashboard array here: https://github.com/GSA/code-gov-about-page/blob/master/index.js#L19

**Comment by saracope** [comment]
Thank you @RicardoAReyes and @DanielJDufour! Fixed this in https://github.com/GSA/code-gov-about-page/pull/7. It will update in the dashboard with the next release.

**Comment by RicardoAReyes** [comment]
👍
