### ISSUE TITLE
Issue when selecting multiple agencies

### ISSUE THREAD

**Issue by saracope** [GSA/code-gov-front-end#153]
**Describe the bug**

Selecting more than one agency from the Browse Project filter does not work. The list defaults back to the full list of agencies.

**To Reproduce**
1. Go to 'Browse Projects'
2. Click on more than one agency in the filters box
3. The repo list resets and shows all repos

**Expected behavior**

Only repos for the selected agencies should display.

**Screenshots**

<img width="1430" alt="screen shot 2019-02-28 at 1 47 31 pm" src="https://user-images.githubusercontent.com/2197515/53590536-f6cbe400-3b5f-11e9-93ee-984425afe9e8.png">

**Comment by ftonato** [comment]
Hello,

I did a simple request to see the _params/response_ and I identified that our problem are on the _backend_, because the _frontend_ is sending all data...

```javascript
agency.acronym = [
  0: usaid,
  1: cfpb,
  2: usda
]
```
![fail](https://user-images.githubusercontent.com/5417662/54426026-b9925500-470e-11e9-939f-6236988400b7.PNG)

**Comment by saracope** [comment]
This was fixed with changes on the back end by @bjbhatt in https://github.com/GSA/code-gov-adapters/pull/5. Thanks!
