### ISSUE TITLE
HomePage WNTR in Featured Projects - Wrong Agency cited?

### ISSUE THREAD

**Issue by amcmanus2019** [GSA/code-gov-front-end#157]
The WNTR project example under Featured Projects says: "developed by Environmental Protection Agency." When you click on "View Project" (https://code.gov/projects/doe_sandia_national_laboratories_snl_water_network_tool_for_resilience_v_1_0) it's identified as a DOE, Sandia NL project. When you click "View the Repo" (https://github.com/usepa/wntr) it's identified as an EPA project and POCs are EPA; however, there's info at the bottom on both EPA and Sandia. So maybe it's a joint project? Should probably be clarified either way in the homepage description and "View Project" site.

**Comment by saracope** [comment]
It looks like this project is being cataloged by DOE and EPA. We have 2 entries for it:
https://code.gov/search?page=1&query=wntr&size=10&sort=best_match

@RicardoAReyes Can this be removed from one of the agency code inventories so it's only being cataloged once?

**Comment by RicardoAReyes** [comment]
@saracope @amcmanus2019 I will reach out to DOE today to address their WNTR entry, clearly the project belongs to EPA.

**Comment by saracope** [comment]
Moved this issue to the code-gov repo since we're removing these featured projects from the home page in the current redesign.

https://github.com/GSA/code-gov/issues/41
