### ISSUE TITLE
Changes to enhance contributor experience

### ISSUE THREAD

**Issue by saracope** [GSA/code-gov-front-end#163]
Currently working with UX Designer to research and develop actionable steps to take in order to create a better experience for those who would like to contribute to the Code.gov project. Research is in progress and tasks will be added as they are identified.

**Comment by ftonato** [comment]
Hello,

I have a suggestion to `Commit Message Style Guide`:

Consider read these references:

- http://karma-runner.github.io/3.0/dev/git-commit-msg.html
- https://dev.to/pavlosisaris/git-commits-an-effective-style-guide-2kkn
- https://udacity.github.io/git-styleguide/

**Comment by saracope** [comment]
I've added cards for actions items on the specific GitHub repos and on our Trello board. Closing this card out.
