### ISSUE TITLE
SBA Windows PC with Edge browser  issue with repo pagination 

### ISSUE THREAD

**Issue by RicardoAReyes** [GSA/code-gov-front-end#170]
Our SBA liaison is using a computer with Windows OS running Edge browser. The user is browsing the Code.gov website, reviewing All repos.  However, the user cannot use the repo pagination, apparently there is no action when the user clicks on the page numbers or next button hyperlink. 

**To Reproduce**
1. Go to https://www.code.gov/browse-projects?page=1&size=10&sort=data_quality
2. Click on the pages or next button hyperlinks. 
3. According to user there is no action on hyperlinks. 
4. Request for Code.gov validate functionality on Edge browser and determine if the issue is valid or false positive. 
5. Perhaps SBA Network or browser setting may be blocking some JS functionality.

**Comment by saracope** [comment]
@RicardoAReyes Can you tag this user here so we can work with them on the fix here?

**Comment by jcastle** [comment]
Limited follow-through and haven't been able to replicate issue. Closing for now.
