### ISSUE TITLE
Incorrect Repo Sorting Order by Data Quality Score 

### ISSUE THREAD

**Issue by RicardoAReyes** [GSA/code-gov-front-end#192]
The code.gov Data Quality Score sorting is not considering the decimal point on it's sorting list. Right now the sorting list is incorrect where repos with higher quality score are shown after lower quality score repos. 

**To Reproduce**
1. Go to https://code.gov/browse-projects?page=1&size=10&sort=data_quality
2. Click on Sort by "Data Quality" 
3. Scroll down the list.
4. Notice how some projects with 7.1 data quality score are shown before repos with 7.4 and 7.2 data quality score. 

**Expected behavior**
The list of projects when sorted by Data Quality Score should be shown in descending order from highest to lowest score. 

**Screenshots**
![sorting_error-1](https://user-images.githubusercontent.com/2433138/57938075-569b7680-7895-11e9-8f63-e5ad206aa6c6.gif)

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser: Chrome, Safari, FireFox
 - Version: most current.

**Comment by lenndachen** [comment]
export function sortByDataQuality(a, b) {
  return sortByDataQuality.sort([comparefunction(a,b)])<0
}

**Comment by GrooveCS** [comment]
Is this still an open issue?

**Comment by jcastle** [comment]
Closing issue as data quality score is being removed with release v1.5.
