### ISSUE TITLE
Update README.md with contact info

### ISSUE THREAD

**Issue by saracope** [GSA/code-gov-front-end#194]
Update the README.md file **Questions?** section with the following info:

Twitter: [@CodeDotGov](https://twitter.com/CodeDotGov)
Email: code@gsa.gov
LinkedIn: [code-gov](https://www.linkedin.com/company/code-gov)
Join our #opensource-public Slack channel: https://chat.18f.gov/

**Comment by ftonato** [comment]
Hello,

I believe that the best tools, among them, would be e-mail and/or Slack.

The other two (Twitter and LinkedIn) don't seem to serve this purpose.

> I even sent a tweet some time ago for the profile above and I never had a response ¯ \ _ (ツ) _ / ¯
