### ISSUE TITLE
URL Doesn't Update when Select Agency in /browse-projects

### ISSUE THREAD

**Issue by DanielJDufour** [GSA/code-gov-front-end#205]
**Describe the bug**

URL should update f I select Consumer Financial Protection Bureau on https://code.gov/browse-projects

**To Reproduce**
1. Go to https://code.gov/browse-projects
2. Select Consumer Financial Protection Bureau in Agency Filter Box

**Expected behavior**

URL should include `agencies=CFPB`

**Screenshots**

![image](https://user-images.githubusercontent.com/4313463/58446931-a3baec00-80d0-11e9-9a16-ac5e682c7edb.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] ChromeOS
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 74

**Additional context**

None, but happy to answer any questions :-)

**Comment by CourtneyBrousseau** [comment]
It seems like this issue only occurs if you go directly to code.gov/browse-projects. I wasn't able to reproduce the issue when I visited the Browse Projects page using the menu from the homepage

**Comment by jcastle** [comment]
It looks like agency is now added to the URL. 

<img width="1440" alt="Screen Shot 2020-01-23 at 11 55 45 AM" src="https://user-images.githubusercontent.com/5223678/73005666-544fcb80-3dd7-11ea-87b1-0be756ce08bb.png">
