### ISSUE TITLE
Consider adding a git commit message style guide

### ISSUE THREAD

**Issue by saracope** [GSA/code-gov-front-end#210]
From @ftonato:

Hello,

I have a suggestion to Commit Message Style Guide:

Consider read these references:

http://karma-runner.github.io/3.0/dev/git-commit-msg.html
https://dev.to/pavlosisaris/git-commits-an-effective-style-guide-2kkn
https://udacity.github.io/git-styleguide/

**Comment by jcastle** [comment]
@saracope, not sure I understand why we would do this and where it would reside on the front-end. Can you elaborate?

**Comment by jcastle** [comment]
Not sure this is a necessity right now. Going to close to reduce clutter.
