### ISSUE TITLE
Home Page display Issues with IE 11

### ISSUE THREAD

**Issue by DanielJDufour** [GSA/code-gov-front-end#268]
**Describe the bug**

There's some styling issues with the new home page when displayed in IE 11

**To Reproduce**
1. Go to 'https://code.gov on IE 11

**Expected behavior**

Same formatting as on Chrome

**Screenshots**

![image](https://user-images.githubusercontent.com/4313463/60901208-8a629f00-a23b-11e9-966f-2f1ba59987cb.png)
![image](https://user-images.githubusercontent.com/4313463/60901253-a1a18c80-a23b-11e9-8b26-fb3d30f1f202.png)
![image](https://user-images.githubusercontent.com/4313463/60901281-acf4b800-a23b-11e9-9170-416a0301a479.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Internet Explorer (via BrowserStack.com)
 - Version [e.g. 22] 11

**Additional context**

**Comment by ftonato** [comment]
Helly my friends,

This problem is related to style that is using _CSS Grid_:

```scss
#explore .explore-actions {
    display: grid;
    // ...
}
```

We can use _Autoprefixer CSS (https://github.com/postcss/autoprefixer)_ to "try to fix" this problem, but perhaps the best approach would be to use fallbacks for unsupported styles, such as CSS Grid / Flexbox.

**Comment by DanielJDufour** [comment]
fyi, @saracope , I'm still seeing issues on IE 11.  Not sure if it's on my end though.  I'm using BrowserStack to test:
![image](https://user-images.githubusercontent.com/4313463/64614077-af8f9d00-d3a5-11e9-9166-af5bb7b53200.png)

**Comment by saracope** [comment]
@DanielJDufour These changes haven't been pushed to production yet.
