### ISSUE TITLE
A button to download code.json for everything and text warning for how big that is.

### ISSUE THREAD

**Issue by JustinGOSSES** [GSA/code-gov-front-end#269]
**Is your feature request related to a problem? Please describe.**
Not a problem, a feature request.

**Describe the solution you'd like**
A single JSON with all code.json files for different repositories combined into a single one.
Somewhere on the site where I could stumble across it or a link to it that points to code.gov/code.json such that it mimics the other code. pages. I looked for this but couldn't find it. Creating it from the API seems time consuming and bothersome, rather it just be there.

**Describe alternatives you've considered**
A repository on github where a single JSON exists, or all the JSONs exist, or an API call that returns it.

**Additional context**
Would be the quickest way for people to make aggregate views of their own. Be nice for hackathons, etc.

**Comment by JustinGOSSES** [comment]
Started Observable notebook that uses API to pull all the repos into a single JSON that is downloadable via button. 

https://observablehq.com/@justingosses/code-gov-demo-dataset-retrieval

Working on converting JSON into CSV in same notebook but that's harder.

**Comment by DanielJDufour** [comment]
Awesome work. Check out https://observablehq.com/@danieljdufour/csv-of-licenses-of-projects-on-code-gov

**Comment by jcastle** [comment]
We are having conversations about a whole government json file. The API will have to do for now.
