### ISSUE TITLE
Add organization to Browse Projects and Project Card

### ISSUE THREAD

**Issue by leebrian** [GSA/code-gov-front-end#285]
**This is a new feature request.**

The code.json schema includes an optional organization field for each release field. If this information were included on code.gov and displayed in the [browse projects page](https://code.gov/browse-projects?&agencies=HHS&page=1&size=10&sort=data_quality) and the [individual project info cards](https://code.gov/projects/hhs_centers_for_disease_control_prevention_1_alignmentviewer), this would help customers better find, understand, use, reuse, and contribute to projects.

**Describe the solution you'd like**
To help organize information, please include organization as a filter criteria in browse. Add organization to the information searched when a user enters text in the search box.
To help display information in the browse results, please add organization near the agency field display and on the individual card, please add organization near the project title.

**Describe alternatives you've considered**
I don't know of an easy way to even view the organization that maintains a project. Currenly, I only to directly scrape the code.json from each agency (eg [www.hhs.gov/code.json](https://www.hhs.gov/code.json)) and manually grep looking for the field, if present. For my agency, we have 56 projects from across multiple sub organizations, opdivs, and staffdivs included in the catalog so this is pretty difficult. I imagine that other agencies with larger number of projects this is much harder so the value to customers would be higher.

**Comment by leebrian** [comment]
I just noticed, that this same feature is mentioned in comments of #91 even though that issue is about something else (displaying tags). Figured I would link it here to help.

**Comment by jcastle** [comment]
Looks like this was completed with PR #325
