### ISSUE TITLE
Add releases.homepageURL to browse project and project card

### ISSUE THREAD

**Issue by leebrian** [GSA/code-gov-front-end#286]
**Is your feature request related to a problem? Please describe.**
This is a new feature request for enhanced usability. The [Browse Projects page](https://code.gov/browse-projects?page=1&size=10&sort=data_quality) and the [Project card](https://code.gov/projects/treasury_bureau_fiscal_service_bfs_1_data_act_broker_backend) display a button labeled "Visit Repo" that links to the URL provided in the code.json release.repositoryURL field. For [some projects ](https://code.gov/projects/hhs_centers_for_disease_control_prevention_1_microbetrace) this links directly to the [git repo](https://github.com/CDCgov/MicrobeTrace.git) and can't be easily viewed in a browser and will launch the user's preferred git client that handles .git files, if they have one installed.

[Code.json schema](https://code.gov/about/compliance/inventory-code) contains an optional field, releases.homepageURL, with the description "The URL of the public release homepage." that might be helpful to display, when it is populated, so users can navigate to a project's web page to learn more about the project.

**Describe the solution you'd like**
Add a "Visit Homepage" button or link on the browse projects list and individual project cards.

**Describe alternatives you've considered**
I can't find any display of the homepageURL field from code.json, so I google the project name and hopefully find the project.
Since GitHub seems to follow a consistent pattern, I can manually remove the .git from the repositoryURL and go directly to the project web page instead of the repo. This is frustrating for me, and likely confusing or not well understood by users not familiar with GitHub's repo url patterns.

**Additional context**
My agency uses the [LLNL/scraper](https://code.gov/projects/doe_lawrence_livermore_national_laboratory_llnl_1_scraper) project to autogenerate our code.json that populates the repositoryURL field so there could be quite a few agencies that will be improved by this feature request.

**Comment by jcastle** [comment]
@leebrian, I am leaning towards closing this because I think it might be confusing to have "visit homepage" and "visit repo" on the same card. Since we are promoting code, we ultimately want them to visit the code. What am I missing here?

**Comment by leebrian** [comment]
I think the problem is that git repos aren't accessible in a browser, so if a user clicks on "go to repo," they'll get an error message. But it's useful to be able to navigate directly to a project's home page in a browser.

For example, here's a [CDC project](https://code.gov/search?&page=1&query=MicrobeTrace&size=10&sort=best_match)...
![Screen Shot 2020-10-05 at 3 53 24 PM](https://user-images.githubusercontent.com/307968/95125560-27540680-0723-11eb-9829-f7cc108b9d65.png)

The "Go to Repo" button's target is [git://github.com/CDCgov/MicrobeTrace.git](git://github.com/CDCgov/MicrobeTrace.git) so if I click on that button, I get an error because my browser doesn't understand that kind of link.

I expect that most users will want to go to the project's homepage in their browser. The url for that project's home page is https://github.com/CDCgov/MicrobeTrace, but isn't visible on the card.

**Comment by jcastle** [comment]
@leebrian, this makes sense. When I was poking around to replicate, I didn't find a "go to repo" leading me to a .git url so it was hard to understand why having the homepage url link was necessary. Got it now. Thanks!

**Comment by leebrian** [comment]
NP, it's kind of hard to replicate as it seems like lots of projects include a url to a renderable page instead of an actual repo. But the schema seems to distinguish this as repositoryURL is the actual repo and homepageURL is the web page. I guess LLNL generates these links for us where repositoryURL is the .git URL and I guess that's handy for someone wanting to clone the repo (or automatically clone them all) but it a pain to just read about the project.

**Comment by jcastle** [comment]
Hi @leebrian, the project cards by repo are being changed to agency cards due to elimination of the API with release v1.5. I am going to close this issue due to this new path forward. Thanks!
