### ISSUE TITLE
Implement Helmet for SEO

### ISSUE THREAD

**Issue by DanielJDufour** [GSA/code-gov-front-end#30]
https://github.com/nfl/react-helmet/blob/master/README.md

**Comment by DanielJDufour** [comment]
@jlow81 , with Helmet we can have a different title and description on our webpage for each project.  This will increase our indexed projects' visibility on search results.  In other words, if someone types in Open Mission Control into Google, they are more likely to see the page on code.gov for it.

**Comment by DanielJDufour** [comment]
We'll also have to decide on the "copy" or text that we want in the `<title>` and `<description>` tags

**Comment by jlow81** [comment]
@DanielJDufour Are we able to do this dynamically and pull the title and description from the API?

**Comment by DanielJDufour** [comment]
@jlow81 , yes.

What should the page title be? Just the repo name or something like `Code.gov - Repo Name`?

What about the description? Should I just use the description from the API?

**Comment by jlow81** [comment]
Coge.gov - Repo Name is good

and, yes, use the description from the API.

**Comment by DanielJDufour** [comment]
I spoke with a community member who will try to implement this over the next 2 days.

**Comment by saracope** [comment]
It looks like that project is no longer being maintained and folks are moving to: https://github.com/staylor/react-helmet-async

**Comment by jcastle** [comment]
Going to close. Been a while and probably won't do this. Thanks for the suggestion.
