### ISSUE TITLE
Console.log() in Production environment?

### ISSUE THREAD

**Issue by BalajiJBcs** [GSA/code-gov-front-end#333]
**Bug Description**
Console.log is been patched with the production codebase, which results in the information been shown in the production environment. It is possible that some confidential details may be leaked.

**To Reproduce**
1. In the Codegov website and ctrl+shift +i to open the developer console where a list of console logs will be shown.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/31539453/69655132-eff4e200-109b-11ea-9b66-f2e2d9d7560f.png)

**Desktop:**
 - OS: [MAC]
 - Browser [chrome,]

Example
https://github.com/GSA/code-gov-front-end/blob/master/src/components/home/home.component.js#L12

**Comment by BalajiJBcs** [comment]
Example:
https://github.com/GSA/code-gov-front-end/blob/master/src/components/home/home.component.js#L12

**Comment by jcastle** [comment]
@BalajiJBcs, I don't see console.log() on the home page anymore. I believe we fixed with an update. If you see it, let me know.
