### ISSUE TITLE
Exclude USWDS from Code Coverage

### ISSUE THREAD

**Issue by saracope** [GSA/code-gov-front-end#334]
**Describe the issue**

Project currently has a maintainability rating of C in Code Climate. Many of the issues are related to the USWDS files. We shouldn't be scanning these as they aren't edited/maintained by this team.

Code Climate issues list: https://codeclimate.com/github/GSA/code-gov-front-end/issues

Task: Update [.codeclimate.yml](https://github.com/GSA/code-gov-front-end/blob/master/.codeclimate.yml) to exclude `styles/uswds` from scanning in Code Climate.
This can only be done by a team admin.

CC docs reference: https://docs.codeclimate.com/docs/excluding-files-and-folders#section-pattern-format

**Comment by afomi** [comment]
https://github.com/GSA/code-gov-front-end/pull/356

**Comment by afomi** [comment]
https://docs.codeclimate.com/docs/excluding-files-and-folders

**Comment by jcastle** [comment]
Closed with merge of PR #356
