### ISSUE TITLE
Policy page -Move section heading out of the white box

### ISSUE THREAD

**Issue by jlow81** [GSA/code-gov-front-end#40]
**Describe the bug**
The heading of each policy section should be outside the white content area

**Screenshots**
![image](https://user-images.githubusercontent.com/29412125/48140522-f210b680-e276-11e8-9faa-86bb1dbb69ed.png)

Should be:
![image](https://user-images.githubusercontent.com/29412125/48140549-03f25980-e277-11e8-8e85-50f4292e85a3.png)

**Comment by saracope** [comment]
We've removed the gray page background with the latest design update, so this is no longer an issue. Closing out.
