### ISSUE TITLE
Bottom of FE site

### ISSUE THREAD

**Issue by anna-zhang** [GSA/code-gov-front-end#406]
Differences for bottom of FE on site.

- [ ] Decide to keep or get rid of Return to top hyperlink at bottom of every page

- [ ] Footer area height is too large

- [ ] Social icons are a different color (should be gray). After clicking on the link, it should stay the same color. Right now, if you click on the link, it turns blue. Production does not have the on-hover change to teal. 

- [ ] Extra Github social icon that the production footer does not have

- [ ] Extra email code@gsa.gov that the production footer does not have

- [ ] U.S. General Services Administration text is not formatted the same as production (not aligned next to logo, different font/color/size). It is also missing the on hover change to teal color. 

- [ ] Footer menu items in production site do not change to teal & underline on-hover; instead, they have a thicker dark blue underline.

**Footer formatted differently:** if you shrink browser page/view on smaller screen, the nav bar stays spread out across horizontally, whereas in production:

- [ ] The GSA logo would disappear
- [ ] navbar shifts to vertical
- [ ] Social icons shift to vertical display (lie on top of each other)
- [ ] U.S. General Services Administration changes color to a muted blue/gray to match the nav bar menu items instead of blue
- [ ] U.S. General Services Administration on hover has an underline in teal

**Comment by jcastle** [comment]
Completed as noted on other project cards.
