### ISSUE TITLE
Homepage FE

### ISSUE THREAD

**Issue by anna-zhang** [GSA/code-gov-front-end#407]
Homepage differences
- [x] “Sharing America’s Code” should be right under the nav bar (there’s currently a gap between the blue banner and the nav bar)
- [ ] Text colors & fonts different in the search area for FIND CODE and the table (Developers/Connect with Us/Agency Partners)
- [ ] Titles need to be bolded (About Code.gov, Open Source News & Events, article/blog post titles)
- [ ] Vision & Mission different font and needs to be bolded
- [x] Update search bar (center placeholder text, italicize, font)
- [x] format About and News
- [ ] Change buttons to usa-button

**Comment by jcastle** [comment]
Completed as noted on other project cards.
