### ISSUE TITLE
About Page FE 

### ISSUE THREAD

**Issue by anna-zhang** [GSA/code-gov-front-end#408]
Differences for all About sections. Some of this is repetitive (e.g. fonts, text color that need to be updated throughout the pages).
- [x] Side navbar breadcrumbs not aligned (Home > About is indented)

**Overview**
_Introduction_
- [x] Header texts (Introduction / About the Source Code Policy / How we’ll get there) are wrong font
- [ ] Body text should be a muted blue instead of black
_Tracking Progress_
- [x] Header texts are wrong font
- [ ] Body text should be a muted blue instead of black
- [ ] Block quote text should be a muted blue 

**Compliance**
_Agency Compliance_
- [x] Header texts are wrong font
- [ ] Body text should be a muted blue instead of black (the numbered list is in the right color though)
- [x] Format cards: title text too large; text container too small, needs to be wider
_How to Procure Software_
- [x] Header texts are wrong font
- [ ] Body text should be a muted blue instead of black
- [ ] Block quote text should be a muted blue 
- [ ] Italicized headers (Things to consider during Step 1/Step 2) should also be bolded
- [ ] h3 (Presolicitation / Solicitation, Negotiation, and Award… ) should be bolded
- [ ] h4 is wrong font
_How to Inventory_
- [x] Header texts are wrong font (h2, h3, h4)
- [ ] Body text should be a muted blue instead of black

**Open Source Pilot**
_Introduction, Tools and Resources, How to Measure, Licensing_
- [x] Header texts are wrong font
- [ ] Body text should be a muted blue instead of black
- [ ] Block quote text should be a muted blue

**Comment by jcastle** [comment]
Completed as noted on other project cards.
