### ISSUE TITLE
Developers Page FE

### ISSUE THREAD

**Issue by anna-zhang** [GSA/code-gov-front-end#409]
Differences for Open Tasks page (other ones redirect to external links):

- [ ] The search results header needs to be formatted. “There are 50 open tasks” is not aligned properly. Missing the top and bottom border around this div. Wrong font weight and font.
- [x] Header texts are wrong font
- [ ] The filter menus on the left don’t have enough space between them vertically
- [ ] The size of the Open Tasks cards are too wide, at the bottom of the page instead of on the right side next to the left filter menu
- [ ] Footer/bottom especially messed up here:
![image](https://user-images.githubusercontent.com/31214438/83657023-4af91b80-a58e-11ea-8544-fdf085cbb03d.png)

**Comment by jcastle** [comment]
Completed as noted on other project cards.
