### ISSUE TITLE
Browse Projects Page

### ISSUE THREAD

**Issue by anna-zhang** [GSA/code-gov-front-end#412]
- [ ] project information not aligned with breadcrumbs

- [ ] title text wrong size and weight

- [ ] Last Updated wrong size and weight

- [ ] icons are the wrong color

- [ ] project text is the wrong color and size

- [ ] project tags need to be spaced out

- [ ] repo features/information should be horizontal across the page

**Comment by jcastle** [comment]
Completed as noted on other project cards.
