### ISSUE TITLE
Styles Under styles Folder

### ISSUE THREAD

**Issue by anna-zhang** [GSA/code-gov-front-end#442]
- [ ] _main
- [x] base-filter-page
- [x] compliance-dashboard
- [x] gov-banner
- [x] json-schema
- [X] menu 
- [x] overrides
- [x] repo-card
- [x] repo-list
- [x] roadmap
- [x] search

**Comment by jcastle** [comment]
Going to leave _main.scss for now. Has a couple "@" links.
