### ISSUE TITLE
SAM.gov Contract Ops JSON API App

### ISSUE THREAD

**Issue by km4391** [GSA/code-gov-front-end#474]
Dear Code.GOV SYS ADMIN :::

There is no example application to query and render the JSON data that you might get from using the Beta.sam.gov API.  The URLs works with my key and world, but -

Is there any open source tool to extract and display the info as a table ? 
Is there an example where you don't need to use the URL bar?
Is there a reason the FSD.gov did not answer this question when I opened a ticket there?
How come excel does not pull the data correctly?
Can you do a keyword search using the API example Search all small business set asides that mention "Solar"?

Thanks ANY HELP will HELP

KEV

**Comment by seanstar12** [comment]
@km4391 I think you have the wrong repository. This is for the code.gov front-end and not for beta.sam.gov or fsd.gov.

**Comment by jcastle** [comment]
@km4391, I am with @seanstar12 on this one. You will want to reach out to the Sam team via their repo or site.
