### ISSUE TITLE
Process to Remove Stale Help-Wanted Tasks

### ISSUE THREAD

**Issue by GrooveCS** [GSA/code-gov-front-end#475]
**Describe the bug**

Create a process to remove stale help-wanted tasks from [Explore Open Tasks](https://code.gov/open-tasks). The following are either stale or archived. 

1. [Search Bar: Pressing down/up arrow on keyboard should move through suggested search options](https://github.com/GSA/code-gov-web/issues/492) - Project: [code-gov-web](https://code.gov/projects/gsa_gsa_1_code_gov) Agency: [General Services Administration](https://code.gov/browse-projects?agencies=GSA) Last Updated: 10/23/2018

1. [Add th cells to Activity Log](https://github.com/cfpb/consumerfinance.gov/issues/977) - Project: [consumerfinance.gov](https://code.gov/projects/cfpb_1_consumerfinance_gov) Agency: [Consumer Financial Protection Bureau](https://code.gov/browse-projects?agencies=CFPB) Last Updated: 4/18/2018

**To Reproduce**

1. Go to  [Open Tasks](https://code.gov/open-tasks)
1. Click on select `Skill Level > Beginner` and `Time Required > Small to filter`
1. Scroll down to _Search Bar: Pressing down/up arrow on keyboard should move through suggested search options_

**Expected behavior**

To see current and open `help-wanted` issues

**Screenshots**

N/A 

**Desktop (please complete the following information):**
 - OS: Win 10 
 - Browser: Chrome
 - Version: Version 84.0.4147.135 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
N/A 

**Additional context**

N/A

**Comment by jcastle** [comment]
Thanks @GrooveCS for submitting this. We will take a look and consider an update.

**Comment by jcastle** [comment]
@GrooveCS, agencies provide issues in Open Tasks by using metadata tags (See [agency instructions](https://github.com/GSA/code-gov/blob/master/docs/help_wanted.md) for more info.). When we harvest the agency code.json file, we use the GitHub API to pick up some extra metadata elements and open issues where agencies would like some help. We don't want to get in the business of removing agency items but we will make this a point of discussion in our upcoming community of practice calls. That should help to get some agencies to update their issues. Thank you for submitting!
