### ISSUE TITLE
Update metadata link for calculating data quality scores

### ISSUE THREAD

**Issue by jcastle** [GSA/code-gov-front-end#477]
Email received by Code.gov team.

----

Hi,

I was trying to understand how you compile the quality score for projects. The "metadata schema" link (https://code.gov/about/compliance/inventory-code) redirects me back to the homepage. Is there an updated link for the schema and also for the code.json file (https://code.gov/about/compliance/inventory-code)? Thanks.

--
Kim Lewandowski | Product Manager, Google Cloud Platform | klewandowski@google.com

**Comment by ftonato** [comment]
Hey,

How should we deal with this "error"?

Could I pick up this one?

**Comment by jcastle** [comment]
Metadata quality scores being removed with v1.5.
