### ISSUE TITLE
Data Quality score helper has invalid urls

### ISSUE THREAD

**Issue by dankolbman** [GSA/code-gov-front-end#506]
**Describe the bug**
Links in the tooltip for the Data Quality Score lead to a non-existent page:
https://code.gov/about/compliance/inventory-code

**To Reproduce**
1. Go to '[Projects](https://code.gov/browse-projects)'
2. Click on '❓' next to 'Data Quality Score'
3. Click on 'code.json' or 'metadata schema' links
4. Both redirect to homepage

**Expected behavior**
'code.json' should link to a page with the code.json spec. 'metadata schema' should navigate to a page with more info about the metadata schema.

**Screenshots**
<img width="759" alt="Screen Shot 2020-10-15 at 11 53 10 AM" src="https://user-images.githubusercontent.com/2495894/96155155-9aa50780-0edd-11eb-966e-e6e04cc0896c.png">

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Comment by jcastle** [comment]
Thanks @dankolbman! We will take a look.

**Comment by jcastle** [comment]
Hi @dankolbman, closing this issue as we have it documented in issue #477. Thanks!
