### ISSUE TITLE
agency compliance dashboard

### ISSUE THREAD

**Issue by mhart-epa** [GSA/code-gov-front-end#514]
11/23/2020 if this isn't going to be assigned, can i get contact info? someone i can talk to?
11/20/2020 how are the tasks determined to be red, yellow or green?

**Comment by jcastle** [comment]
Hi @mhart-epa, we are updating the site now. Please review the compliance dashboard and let me know if you still have the same questions.

**Comment by mhart-epa** [comment]
thanks Joseph

I was under the impression that GSA pulled code.json files hanging off the agency domain, e.g.., epa.gov/code.json? does the file need to be pushed instead?

thanks again and stay safe! mike/202-566-1696

**Comment by jcastle** [comment]
The program funding has been cut so we had to turn off the API. We are no longer harvesting agency code.json files, rather we are pointing to where they reside along with any other agency code we know about on GitHub or other places. I am going to close for now unless there is an issue with your agency data currently on the site.
