### ISSUE TITLE
No Mobile View of JSON Schema Viewer

### ISSUE THREAD

**Issue by DanielJDufour** [GSA/code-gov-front-end#52]
**Describe the bug**
User can't scroll left and right to see the schema explanation table

**To Reproduce**
1. Go to https://staging.code.gov/about/compliance/inventory-code

**Expected behavior**
Scroll left and right, but ideally have a version of this viewer that is more mobile friendly

**Screenshots**
![image](https://user-images.githubusercontent.com/4313463/48394836-13442d80-e6e3-11e8-9b51-77b5fb2b60b4.png)

**Smartphone (please complete the following information):**
Samsung S5

**Additional context**
@jlow81 , do we a mockup for the mobile version of the schema viewer?

**Comment by jlow81** [comment]
@DanielJDufour How about something like this?

![schema_mobile](https://user-images.githubusercontent.com/29412125/48440637-69eb4f00-e757-11e8-885b-25f9c47c9262.gif)

**Comment by DanielJDufour** [comment]
@jlow81 , I really like that.  It would take a few days though.  My recommendation is that I just fix it so people can scroll left and right on the table and I code up this mobile redesign after the migration is complete

**Comment by DanielJDufour** [comment]
We will temporarily tighten the spacing in the table and will work on mobile view post-Monday

**Comment by DanielJDufour** [comment]
I tightened up space. Labeling as backlog, bc mobile view will be done after deployment

**Comment by DanielJDufour** [comment]
90% Complete.  You can view on staging.  @jlow81 , could you QA?

There's two remaining smaller low-priority issues:
 - The details window just appears (without scrolling into view), but does scroll out of view when back is clicked.
 - The user has to scroll up to see the details when they click the details button.  We'll have to discuss what we want the UX to be here.

**Comment by DanielJDufour** [comment]
This was fixed with most recent release.
