### ISSUE TITLE
IE: Home Area Dropdown Looks Wierd

### ISSUE THREAD

**Issue by DanielJDufour** [GSA/code-gov-front-end#71]
**Describe the bug**

**To Reproduce**
1. Go to main page

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/4313463/48496181-7aef9b00-e7ff-11e8-96d7-71827d7276da.png)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] IE

**Additional context**

**Comment by saracope** [comment]
Was this IE 11? @DanielJDufour

**Comment by DanielJDufour** [comment]
@saracope , yes.  This was IE 11.  I'll close this issue though, as the redesign removed this.
