### ISSUE TITLE
Increase width of Data Quality Score corner area

### ISSUE THREAD

**Issue by jlow81** [GSA/code-gov-front-end#8]
**Describe the bug**
The triangle where the Data Quality Score is displayed should be a little wider so it looks more balanced

**Screenshots**
Before and After
![image](https://user-images.githubusercontent.com/29412125/47746247-245d5b00-dc5c-11e8-982b-8006ae50ee4e.png)

**Comment by DanielJDufour** [comment]
@jlow81 , I'm marking as backlog and will do after the rearch.  AFAIK, it's not something that is on the current main site, either.

**Comment by DanielJDufour** [comment]
If someone wants to pick this up, they should look at https://github.com/GSA/code-gov-style/blob/master/_sass/_cards.scss#L21
