### ISSUE TITLE
Clear search button missing

### ISSUE THREAD

**Issue by jlow81** [GSA/code-gov-front-end#84]
On current site:
![image](https://user-images.githubusercontent.com/29412125/48648150-4ffe7600-e9bc-11e8-8684-7c2c74827704.png)

On React site:
![image](https://user-images.githubusercontent.com/29412125/48648166-6278af80-e9bc-11e8-8f5b-4fee631c2ea1.png)

**Comment by DanielJDufour** [comment]
Good catch. Thanks

**Comment by DanielJDufour** [comment]
This will be an easy fix. The clear search button is a built-in feature provided by browsers.  I just have to add `type='search'` to the inputs

**Comment by DanielJDufour** [comment]
Fixed
