### ISSUE TITLE
Reduce Image Sizes

### ISSUE THREAD

**Issue by DanielJDufour** [GSA/code-gov-front-end#87]
**Is your feature request related to a problem? Please describe.**
All the images on the home page greatly reduce the loading speed of the site.  **432** of the 600KB needed to load the site are image data.

**Describe the solution you'd like**
 - Use squoosh from Google to reduce the size of images https://squoosh.app/
 - Use [sharp](https://www.npmjs.com/package/sharp) to create different sizes of the images and include this script in the main code-gov-web package
 - Set image src (i.e. load images) based on the size of the screen. Put this inside of the React code.
 
**Describe alternatives you've considered**
ImageMagic CLI, but that's probably more complicated

**Additional context**
![image](https://user-images.githubusercontent.com/4313463/48728555-3e5adf80-ec03-11e8-9c18-4873e7f160cf.png)
- https://web.dev/fast/serve-images-webp
- https://web.dev/fast/serve-responsive-images

**Comment by jcastle** [comment]
Have three images in News section on homepage and use a reducer before adding pics to assets.
