### ISSUE TITLE
Navigation between pages

### ISSUE THREAD

**Issue by AminPIC** [GSA/code-gov-front-end#90]
Bug:
When navigating from one page to another, the site remembers where you were located on the previous page and automatically sets the user in the same spot in the new page. For example, if you are halfway or at the bottom of the About page and toggle to the Compliance Dashboard, your new location in the Compliance Dashboard will be at either halfway or at the bottom of the page (depending on where you 

**Expected behavior**
The expected behavior is that you would land at the top of each new page you link to.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version  70.0.3538.102

**Comment by DanielJDufour** [comment]
Great catch @AminPIC !  

For whoever works on this, issue is probably that I didn't include [refreshView](https://github.com/GSA/code-gov-front-end/blob/master/src/utils/other.js#L70) in all the places of the code that I should have.  You can see an example of its use [here](https://github.com/GSA/code-gov-front-end/blob/master/src/components/roadmap/roadmap.component.js#L45)

**Comment by DanielJDufour** [comment]
I'll do this

**Comment by DanielJDufour** [comment]
I completed code so it puts the breadcrumbs at the top of the page whenever the user changes the page by clicking a menu option.  (It got annoying having to scroll down past banner every time the page changes).  I now have to get this to work on mobile and when a user clicks the back button in their browser.

**Comment by AminPIC** [comment]
🙌🙌🙌
