### ISSUE TITLE
Display tags on repo browse

### ISSUE THREAD

**Issue by leebrian** [GSA/code-gov-front-end#91]
When browsing or filtering projects, only a very limited set of filters are available- language, agency, license, usage type.

As a user, I would like to filter by tag, to more quickly find projects.
As an agency, CDC, I would like to tag my projects to allow filtering of projects under HHS by agency, but also by topic area of the project such as bioinformatics, epidemiology, etc.

Below is a suggested way to display tags based on the repo detail card.

![image](https://user-images.githubusercontent.com/307968/48806479-6cfeb600-ece8-11e8-8caf-3a4ca6a27b58.png)

**Comment by DanielJDufour** [comment]
Hi, @leebrian .  This is great feedback. Thank you!  We're currently exploring adding a search input into the filter boxes that you see on the left side of the [browse-projects](https://code.gov/browse-projects) and [search](https://code.gov/search?page=1&query=water&size=10&sort=best_match) pages.  Once the user has the ability to search over their filter options, we can probably add a filter box for tags.

My concern right now with the filter boxes is that it's a pain for users to scroll through all of the options.  IMHO, the filter box for languages is already a pain to scroll through.

Although, I have some worries about tagging (mostly around maintenance costs and comparability with automated `tagging` solutions like [LSI](https://en.wikipedia.org/wiki/Latent_semantic_analysis)), you've convinced me of its utility :-)

That said, we'd need to make sure that the tags that appear in the box have valuable content for users.  Would it be fair to only show tags that have at least 2 or more repos?

I should also mention that my colleagues have been brainstorming solutions for filtering repos by subcomponents of agencies, too.  So hope to share that with you when we've confirmed our plans on that.

Happy to brainstorm this :-) Thanks again!

**Comment by leebrian** [comment]
For me, the importance of tags is to help browsers know a little more about projects before drilling down or going to repo. Since CDC is under HHS and thus not an organization per the schema, tags is important to our programs to show how the projects are organized.

I think two or more repos is an acceptable way to filter how many show up and reduce clutter. Maybe even more depending on how many tags you end up having and screen space available. Selfishly, CDC will have lots of projects so anything over 40 is fine with me :)

Happy to join brainstorm. I think that organizations and groups will be useful for sorting and filtering and using the built-in organizational groups in GitHub, GitLab, Sr.Ht, and others will be useful behavior.

**Comment by RicardoAReyes** [comment]
hi @leebrian, we have evaluated the Code.gov platform to support filtering by Agency Component/Subagency/Department. The designs are ready and the engineering team will be implementing a solution in the near future. 

![screen_shot_2018-09-17_at_4 32 13_pm](https://user-images.githubusercontent.com/2433138/48852767-0d51ea80-ed7c-11e8-8752-1dd981b4d0aa.png)

Please use the "organization" property field to specify "CDC" on your releases as described on the [Metadata Schema 2.0.0](https://code.gov/about/compliance/inventory-code).

**Comment by leebrian** [comment]
Thanks, that will fulfill my use case. We currently use organization and will look out for the update.

**Comment by jcastle** [comment]
@leebrian, I am going to close this issue for now because it has become stale and it's not on our short-term radar. As always, thank you for the input.

**Comment by leebrian** [comment]
Of course it's your prerogative to decide what changes to make and when, but I think that it will help future issue submitters to just set it as "closed, won't fix" and add a description of why.

Your current reason is a bit tautological as items are stale and not on your short-term (or long-term radar I assume) because you won't fix them. I think you have a good reason and sharing that reason with me and other readers will help understand the why this isn't fixed. What I mean, is that it's obvious that it's stale as it's two years old. But what is of interest to me is why this wasn't important enough to make a change. 

Was this not implemented due to not enough resources? Due to not liking the UX? Due to it not being important to filter by org? Sharing why a particular issue isn't going to be completed is useful information.

**Comment by jcastle** [comment]
@leebrian, thanks for the thoughtful feedback. Mostly due to resource constraints. The team has been shrinking from 10 to 5 to now 4. We are down to a frontend engineer, backend engineer, agency outreach, and communications where we used to have double the bandwidth in the engineering roles. My focus while getting up to speed on the frontend is to simplify the site (e.g., reduce the number of web components, repos, dependencies to manage) while cleaning up what we do have before considering new work.

With that said, we are an open source project and I appreciate the input but I can only get to so much. Of course PRs are always better than issues. Here is our current [Roadmap](https://code.gov/roadmap). With the current government CR and level of maintenance, I can't promise much else can be addressed. We will continue to revise as we go and can always use the help.

**Comment by leebrian** [comment]
Thanks, that's really helpful and pretty much what I expected. We all need more resources :). It's particularly helpful to know it wasn't a design or UX issue as I want to make sure my suggestions fit into your overall design aesthetic as much as I can.

The roadmap is really helpful, and I'll pile this onto my list of "weekend programming" that may one day result in a PR.
