### ISSUE TITLE
Jump to top of cards when click next

### ISSUE THREAD

**Issue by DanielJDufour** [GSA/code-gov-front-end#93]
**Is your feature request related to a problem? Please describe.**

When I'm going page to page through projects on browse page on mobile, it's annoying to have to scroll through filters everytime
**Describe the solution you'd like**

Maybe jump straight to card results on page change on mobile

**Describe alternatives you've considered**

**Additional context**

**Comment by saracope** [comment]
Closing this one out in favor of the suggestion made in #103 to put the filters a grouping which users could select to expand.
