### ISSUE TITLE
Losing SideNav on About and Policy Guide Pages

### ISSUE THREAD

**Issue by DanielJDufour** [GSA/code-gov-front-end#99]
**Is your feature request related to a problem? Please describe.**

When I scroll down pages on desktop that have a SideNav, I lose the SideNav component as I scroll down.

**Describe the solution you'd like**

 It would be nice if they were sticky, so I could jump to another page without having to scroll back up to the top.

**Describe alternatives you've considered**

Could have a button that replaces the SideNav that when pressed, jumps the user back up to the top, but that would probably be more work.

**Additional context**

![image](https://user-images.githubusercontent.com/4313463/49107516-ea2fab00-f253-11e8-8b01-591f2f61dde6.png)

**Comment by bblair31** [comment]
We'll work on this

**Comment by ftonato** [comment]
Hello,

This issue already resolved.

Check the _GIF_ below:
![issue-resolved](https://user-images.githubusercontent.com/5417662/50451373-802a2480-092b-11e9-877e-dfb53156d70f.gif)
